# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-datadog-monitor
  description: This component is responsible for provisioning Datadog monitors and assigning Datadog roles to the monitors
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component

